config/routes.rb
Rails.application.routes.draw do
    root 'questions#index'
    get '/signup' => 'users#new'
    get '/edit' => 'users#edit'

    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    delete '/logout' => 'sessions#destroy'

    resources :users
    resources :questions do
        member do
            put "like", to:    "questions#upvote"
            put "dislike", to: "questions#downvote"
        end
        resources :answers
    end

    resources :answers do
        member do
            put "like", to:    "answers#upvote"
            put "dislike", to: "answers#downvote"
         end
    end
end






# another way to include voting routes unlike how i have included for questions
# resources :answers do
#   match "vote", action: :vote, via: [:put,:delete], on: :member
# end

# end








# Rails.application.routes.draw do

#   root 'questions#index'

#   get '/signup' => 'users#new'

#   get '/edit' => 'users#edit'


#     get '/login' => 'sessions#new'
#     post '/login' => 'sessions#create'
#     delete '/logout' => 'sessions#destroy'
 
#     resources :users
#         resources :questions do
#             member do
#                 put "like", to:    "questions#upvote"
#                 put "dislike", to: "questions#downvote"
#             end
#         resources :answers
#         end






# # another way to include voting routes unlike how i have included for questions
# resources :answers do
#   match "vote", action: :vote, via: [:put,:delete], on: :member
# end

# end

app/models/answer.rb
class Answer < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  belongs_to :question
  validates :response, presence: true

end

app/models/question.rb
class Question < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
  	validates :title, presence: true
  	has_many :answers, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	has_secure_password
	validates :name, presence: true
	validates :email, presence: true
	has_many :questions, dependent: :destroy
	has_many :answers

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	 def create
		@question = Question.find(params[:question_id])
		@answer = @question.answers.create(params[:answer].permit(:response))
		@answer.user_id = current_user.id if current_user
		@answer.save
		if @answer.save
			redirect_to question_path(@question)
		else
			redirect_to question_path(@question)
			flash[:danger] = "You haven't typed anything Dawg!!" 
		end
	end



  	def edit
		@question = Question.find(params[:question_id])
		@answer = @question.answers.find(params[:id])
	end

	def update
		@question = Question.find(params[:question_id])
		@answer = @question.answers.find(params[:id])

		if @answer.update(params[:answer].permit(:response))
			redirect_to question_path(@question)
		else
			render 'edit'
		end
	end

 	def destroy
		@question = Question.find(params[:question_id])
		@answer = @question.answers.find(params[:id])
		@answer.delete
		redirect_to question_path(@question)
	end

	def upvote
		@answer=Answer.find(params[:id])
		@answer.upvote_by current_user
		redirect_to :back
	end

	def downvote
		@answer=Answer.find(params[:id])
		@answer.downvote_by current_user
		redirect_to :back
	end
	
end


 #  def vote
	# 	if request.put?
	# 	@answer=Answer.find(params[:id])
	# 	@answer.liked_by current_user
	# 	redirect_to :back
	# 	elsif request.delete?

	# 	@answer=Answer.find(params[:id])
	# 	@answer.disliked_by current_user
	# 	redirect_to :back
	# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
   before_action :set_question, only: [:edit, :update, :show, :destroy]
  before_action :logged_in_user, only: [:new, :create, :destroy]
  def new
  	@question=current_user.questions.build
  end

  def create
  	@question=current_user.questions.build(question_params)
  	if @question.save
  		redirect_to @question
  	else
  		render :new
  	end
  end

  def index
  	@questions=Question.all
  end

  def edit
  end

  def update  
      if @question.update(question_params)
        redirect_to root_path
      else
        render :edit
      end  
  end

  def show
  end

  def destroy
    @question.destroy
    redirect_to root_path
  end

  def upvote 
    @question=Question.find(params[:id])
    @question.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @question=Question.find(params[:id])
    @question.downvote_by current_user
    redirect_to :back
  end

  private

  	def question_params
  		params.require(:question).permit(:title)
  	end   	

    def set_question
      @question=Question.find(params[:id])
    end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	
  	user=User.find_by(email: params[:session][:email])
  	if user && user.authenticate(params[:session][:password])
  		flash[:success] = "Logged in"
  		log_in(user)
  		redirect_to user
  	else
  		flash.now[:error] = "Your email or password is incorrect"
  		render action: 'new'
  	end
  end

  def destroy
  	log_out
  	flash.now[:success] = "Bye Bye Lover"
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update, :destroy]
  def index
    @users=User.all
  end

  def new
  	@user=User.new
  end

  def create
  	@user=User.new(user_params)
  	if @user.save
      session[:user_id] =@user.id
      flash[:success] = "Welcome to the Dark Web"
      log_in(@user)
  		redirect_to @user
  	else
      flash[:danger] = "Please correct the errors below" 
  		render :new
  	end
  end

  def edit
  end

    def update
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      flash[:danger] = "Please correct the errors below" 
      render :edit
    end
  end


  def show
  	@user=User.find(params[:id])
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless @user == current_user
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id]=user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def logged_in_user
		unless logged_in?
			flash[:danger] = "Please log in."
        	redirect_to login_path
        end
      end

	def log_out
		session.delete(:user_id)
		@current_user = nil	
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_answer.html.erb
<div class ="each_answer_on_question_page">
	<div class="row">
		<div class="col-md-1 vote-column">
			<h3>
			<div class = "vote">
				<%= link_to "<i class='glyphicon glyphicon-chevron-up'></i> ".html_safe, like_answer_path(answer), method: :put %>
					<%=answer.get_upvotes.size%> </div> <br>
			<div class = "vote">
				<%= link_to "<i class='glyphicon glyphicon-chevron-down'></i> ".html_safe, dislike_answer_path(answer), method: :put %>
				<%=answer.get_downvotes.size%></div>
			</h3>
		</div>

		<div class="col-md-11">
			<p><span class = "answer_user_name"><%=answer.user.name.split[0]%>: </span>
			<span class = "answers-on-show"><%=answer.response.html_safe%></span><br>
			<span class = "time_ago"><%=time_ago_in_words(answer.created_at)%> ago  </span>

			<%if answer.user==current_user%>
			<%= link_to "<i class = 'glyphicon glyphicon-pencil edit-glyph'></i>".html_safe, edit_question_answer_path(answer.question, answer)%>
			<%= link_to "<i class='glyphicon glyphicon-remove delete-glyph'></i> ".html_safe, [answer.question, answer], method: :delete, data: { confirm: "Are you sure?" }%>
			<%end%><br>

			
			</p>
	
			
		</div>
	</div>
</div>

app/views/answers/_form.html.erb
<%if !current_user.nil?%>
	<%=form_for([@question, @question.answers.build]) do |f|%>
	<%= f.label :response, "Your Answer"%><br>
	<%= f.text_area	:response, class: "form-control" %><br>
	<%=f.submit "submit"%>
	<%end%>
<%else%>
<span><%= link_to "Login", login_path%> or <%= link_to "Sign up", signup_path%> to answer this question</span>
<%end%>

app/views/answers/edit.html.erb
<div class = "container">
	<div class= "jumbotron">
		<div class="row">
  			<div class="col-md-10 col-md-offset-1">

<%= form_for([@question, @answer]) do |f| %>
	

	<%= f.label :response, "Update Your Answer"%><br>
<%= f.text_area	:response, class: "form-control"%><br>
<%=f.submit "Update"%>
<%end%>

</div>
		</div>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class = "navbar navbar-inverse">
	<div class="row">
  		<div class="col-md-10 col-md-offset-1">
	  		<div class = "navbar-header">
				<%= link_to "Ask-o-Ans", root_path,  class: "navbar-brand" %>
			</div>
					
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "All Questions", root_path%></li>
				<li><%= link_to "New Question", new_question_path%></li>
				<% if logged_in? %> 
				<li><%= link_to "All Users", users_path%></li>
				<li><%= link_to "Logout", logout_path, method: "delete"%></li>
				<li><%= link_to current_user.name, current_user%></li>
				<% else %>
		     	<li><%= link_to "Sign Up", signup_path%></li>

		      	<li><%= link_to "Login", login_path%></li>
		      	<% end %>
		    </ul>	
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>askoans</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


	<%= render "layouts/navbar"%>

	


<%= yield %>

</body>
</html>

app/views/questions/edit.html.erb
<div class = "container">
	<div class= "jumbotron">
		<div class="row">
  			<div class="col-md-10 col-md-offset-1">
  			<h2>Update Question or Add details</h2>

			<%= form_for @question do |q|%>
				<%= q.label :title, "Ask" %><br>
				<%= q.text_area :title, class: "form-control" %><br>
				<%= q.submit "Submit", class: "btn btn-primary"%>
				<%= link_to "Back", root_path, class: "btn btn-default" %>
			<% end %>
			</div>
		</div>
	</div>
</div>

app/views/questions/index.html.erb
<div class = "container">
	<div class= "jumbotron">
		<div class="row">
        	<div class="col-md-10 col-md-offset-1">
  			   <H3>New Questions</H3>
            </div>
        </div>

        <% @questions.each do |q|%>
            <div class ="row">
  				<div class ="col col-md-1 image-index">
                    <%= image_tag q.user.image.thumb.url%>
                </div>

                <div class = "col col-md-8   question-on-index">
  					<%= link_to q.title, question_path(q), class: 'link-to-text-color'%> <br>

                    <%if logged_in? && current_user.name.downcase.split[0] == "rayaan" && q.user.name.downcase.split[0] == "rayaan"%>
                        <span class= "submitted">--Submitted <%=time_ago_in_words(q.created_at)%> ago by <span class =" heart"> <%=q.user.name%> </span>aka Sunshine
                        </span>
                    <%else%>
                        <span class= "submitted">--Submitted <%=time_ago_in_words(q.created_at)%> ago by <%=q.user.name%>
                        </span>
                    <%end%>

                    <span class = "edit-delete-buttons">
                        <% if current_user == q.user %>
                            <%= link_to "<i class='glyphicon glyphicon-pencil delete-glyph'></i> ".html_safe, edit_question_path(q)%>
                            <%= link_to "<i class='glyphicon glyphicon-remove delete-glyph'></i> ".html_safe, q, method: :delete, data: {confirm: "Are you sure?"}%>
                        <% end%>
                    </span>
                </div>

                <div class ="col col-md-2 answer-count-on-index">
                    <span class = "answer-count"><%=q.answers.count%> ans &nbsp;&nbsp; </span>
                    <span class= "answer-button"> 
  						<%= link_to " Answer it!",question_path(q) %>
                    </span>
                </div>   

		    </div><br>
        <% end%>
  	</div>
</div>

app/views/questions/new.html.erb
<div class = "container">
	<div class= "jumbotron">
		<div class="row">
  			<div class="col-md-10 col-md-offset-1">
  			<% if current_user.name.split[0].downcase == "rayaan"%>
  				<h2 class ="new-question heart"> Hello <i class='glyphicon glyphicon-heart-empty heart'>Ray</i><i class='glyphicon glyphicon-heart-empty heart'></i>, What would you like to know today? Ask away!</h2>
  			<%else%>
  				<h2 class ="new-question heart"> Hello <%= current_user.name.split[0]%>, What would you like to know today? Ask away!</h2>
  			<%end%>

			<%= form_for @question do |q|%>
				<%= q.label :title, "Ask" %><br>
				<%= q.text_area :title, class: "form-control" %><br>
				<%= q.submit "Submit", class: "btn btn-primary"%>
				<%= link_to "Back", root_path, class: "btn btn-default" %>
			<% end %>
			</div>
		</div>
	</div>
</div>

app/views/questions/show.html.erb
<div class = "container">
	<div class= "jumbotron">
	<%flash.each do |msg_type, msg|%>
		<div class ="alert alert-<%=msg_type%>"><%=msg%></div>
	<%end%>
	
		<div class="row">
			<div class="col-md-1 vote-column">
				<div class = "vote"><%= link_to "<i class='glyphicon glyphicon-chevron-up'></i> ".html_safe, like_question_path(@question), method: :put %>
					<%=@question.get_upvotes.size%>
				</div><br>

				<div class = "vote"><%= link_to "<i class='glyphicon glyphicon-chevron-down'></i> ".html_safe, dislike_question_path(@question), method: :put %>
					<%=@question.get_downvotes.size%>
				</div>
			</div>

  			<div class="col-md-1">
  				<%= image_tag @question.user.image.thumb.url%> 
			</div>

			<div class="col-md-9">
				<span class =" question-on-show"><%= @question.title %></span><br>

				<%if logged_in? && current_user.name.downcase.split[0] == "rayaan" && @question.user.name.downcase.split[0] == "rayaan"%>
					<small>Submitted <%=time_ago_in_words(@question.created_at)%> ago by <span class ="heart">rayaan </span> aka The Monkey boy
					</small><br>
				<%else%>
					<small>Submitted <%=time_ago_in_words(@question.created_at)%> ago by <%=@question.user.name%>
					</small><br>
				<%end%>

				<% if !logged_in? %>
				

				
				<small><%= link_to "Login", login_path%> or <%= link_to "Sign up", signup_path%> to answer/rate this question</small>

				<% end %>


				<%= render @question.answers%> <br>
			</div>

			</div>

			<div class = "row">
				<div class = "col col-md-10 col-md-offset-1 ">
					<%= render 'answers/form'%>
				</div>
			</div>
	</div>
</div>

app/views/users/_form.html.erb
	
	<%if @user.errors.any?%>
		<%flash.each do |msg_type, msg|%>
			<div class ="alert alert-<%=msg_type%>">
				<%=msg%>
			</div>
		<%end%>
	<%end%>

	<%=form_for(@user) do |user|%>
		<ul>
			<%@user.errors.full_messages.each do |msg|%>
				<li><%=msg%></li>
			<%end%>
		</ul>

		<p>
		<%= user.label :name%><br>
		<%= user.text_field :name, class: 'form-control'%> 
		</p>

		<p>
		<%= user.label :email%><br>
		<%= user.email_field :email, class: 'form-control'%> 
		</p>

		<p>
		<%= user.label :password%><br>
		<%= user.password_field :password, class: 'form-control'%> 
		</p>

		<p class="field">
    		<%= user.label :image %><br>
    		<%= user.file_field :image %>
    		<% if user.object.image? %>
      <%= image_tag user.object.image.url %>
      <%= user.label :remove_image %>
      <%= user.check_box :remove_image %> 
    <% end %>
 		</p>
		<%= user.submit "Submit", class: 'form-control btn btn-primary'%>
	<%end%>

app/views/users/edit.html.erb
<div class = "container">
<div class= "jumbotron">
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<h1 class = "text-center">Edit</h1>

  	<%= render "form"%>

  		</div>
		</div>
				</div>
						</div>

app/views/users/index.html.erb
<div class = "container">
	<div class= "jumbotron">
		<div class="row">
  			<div class="col-md-6 col-md-offset-3">

				<h2 class= "text-center">List of Users </h2>
				<table>
					<% @users.each do |user|%>
						<tr>
							<td width = 200>
								<%= link_to user.name, user_path(user)%>
							</td>
							<td width = 150>
								<%= link_to "Profile", user_path(user)%>
							</td>
							<%if current_user == user %>
							<td width = 150>
								<%= link_to "Edit", edit_user_path(user)%>
							</td>

							<td width = 150>
								<%= link_to "Delete", user_path(user.id), method: :delete, data: { confirm: "Are you sure you want to delete all details of this user from this application? Think about it again before clicking-ok. You can not reverse this delete. Please proceed with caution. Okay,enough warnings given, now make your choice!"}%>
							</td>
							<%end%>
						</tr>
					<%end%>
				</table>
			</div>
  		</div>
	</div>
</div>

app/views/users/new.html.erb
<div class = "container">
	<div class= "jumbotron">
		<div class="row">
  			<div class="col-md-6 col-md-offset-3">
  				<h1 class = "text-center">Join in</h1>
   				<%= render "form"%>
   				<h3> Already registered? <%= link_to "Login", login_path%></h3>
	  		</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class = "container">
<div class= "jumbotron">
<!-- <div class="row">
  <div class="col-md-10 col-md-offset-1"> -->
<%flash.each do |msg_type, msg|%>
	<%if @user.name.split[0].downcase == "rayaan"%>
		<div class ="alert alert-<%=msg_type%>"><%=msg%>, <%= "Loverboy"%></div>
	<%else%>
		<div class ="alert alert-<%=msg_type%>"><%=msg%>, <%= @user.name.split(" ").shift.capitalize%></div>
	<%end%>
<%end%>
<h2 class = "profile_name"><%= (@user.name).titleize %></h2>

<p>
<!--   <div class="row">
  <div class=" profile_image col col-md-4">
 -->  <%= image_tag @user.image.avatar.url%>
<!--   </div>
  </div> -->


</p>
<%if current_user == @user %>
							
								<%= link_to "Edit Profile", edit_user_path(@user)%>
								<%end%>

<p>
<div class= "page-header">
<!-- <h4><%= (@user.name.split(" ").shift).capitalize%>'s activity</h4></p> </div>
 --><h3>Questions asked</h3>
<% @user.questions.pluck(:title, :id).each do |title, id|%>
<h3><%= link_to title, question_path(id), class: "link-to-text-color" %></h3>
<%end%>
<hr>
<h3>Answers </h3>
<% @user.answers.pluck(:response, :question_id).each do |response, question_id|%>

<h3  class= "link-to-text-color"><%=response%></h3>

<span>In response to: </span><%= link_to Question.find(question_id).title, question_path(question_id), class: "link-to-text-color" %>

<%end%>
	</div>
		</div>
				</div>
						</div>


							